### ISSUE TITLE
Fatal Error after Yellow Update 

### ISSUE THREAD

**Issue by pftnhr** [GiovanniSalmeri/yellow-maintenance#2]
Hi Giovanni,

after an yellow update to 0.8.22 the extension causes a fatal error for me:

`Fatal error: Uncaught Error: Call to undefined method YellowCore::getRequestHandler() in /www/htdocs/w0077d88/seventy-eight/system/extensions/maintenance.php:54 Stack trace: #0 /www/htdocs/w0077d88/seventy-eight/system/extensions/core.php(3144): YellowMaintenance->onParsePageLayout(Object(YellowPage), 'default') #1 /www/htdocs/w0077d88/seventy-eight/system/extensions/core.php(3104): YellowPage->parsePageLayout('default') #2 /www/htdocs/w0077d88/seventy-eight/system/extensions/core.php(195): YellowPage->parsePage() #3 /www/htdocs/w0077d88/seventy-eight/system/extensions/core.php(141): YellowCore->sendPage('https', 'krautsuppe.de', '/eighty-seven...', '/', 'content/1-home/...', false, true) #4 /www/htdocs/w0077d88/seventy-eight/system/extensions/edit.php(297): YellowCore->processRequest('https', 'krautsuppe.de', '/eighty-seven...', '/', 'content/1-home/...', false) #5 /www/htdocs/w0077d88/seventy-eight/system/extensions/edit.php(276): YellowEdit->processRequestShow('https', 'krautsuppe.de', '/seventy-eight...', '/', 'content/1-home/...') #6 /www/htdocs/w0077d88/seventy-eight/system/extensions/edit.php(68): YellowEdit->processRequest('https', 'krautsuppe.de', '/seventy-eight...', '/', 'content/1-home/...') #7 /www/htdocs/w0077d88/seventy-eight/system/extensions/core.php(106): YellowEdit->onRequest('https', 'krautsuppe.de', '/eightseventy...', '/', 'content/1-home/...') #8 /www/htdocs/w0077d88/eightseventy/yellow.php(9): YellowCore->request() #9 {main} thrown in /www/htdocs/w0077d88/eightseventy/system/extensions/maintenance.php on line 54`.

Do you have any ideas?

Your linked zip also seems to contain an older version. The maintenance.php in there has April 2022 as the date.

**Comment by GiovanniSalmeri** [comment]
Thank you very much for alerting me: I had missed a change in the new API. After updating the extension all should work, can you confirm?

**Comment by pftnhr** [comment]
> Thank you very much for alerting me: I had missed a change in the new API. After updating the extension all should work, can you confirm?

All works fine now. Thank you!
